#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x73b49816, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x326ec07b, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xb758258f, __VMLINUX_SYMBOL_STR(sock_no_getsockopt) },
	{ 0x7946b8bc, __VMLINUX_SYMBOL_STR(sock_no_setsockopt) },
	{ 0x6f7bb7f9, __VMLINUX_SYMBOL_STR(sock_no_shutdown) },
	{ 0x345507da, __VMLINUX_SYMBOL_STR(sock_no_listen) },
	{ 0xc4503884, __VMLINUX_SYMBOL_STR(sock_no_ioctl) },
	{ 0xeaa3d3ab, __VMLINUX_SYMBOL_STR(datagram_poll) },
	{ 0x4186d4be, __VMLINUX_SYMBOL_STR(sock_no_getname) },
	{ 0x92e277c6, __VMLINUX_SYMBOL_STR(sock_no_accept) },
	{ 0xaad670ff, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0x9e4bafa1, __VMLINUX_SYMBOL_STR(sock_no_connect) },
	{ 0xed11113e, __VMLINUX_SYMBOL_STR(sock_no_bind) },
	{ 0x5ca3f49f, __VMLINUX_SYMBOL_STR(seq_release_net) },
	{ 0x2a6d5b4e, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0x9f48f773, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0xc5c44ec7, __VMLINUX_SYMBOL_STR(xfrm_register_km) },
	{ 0x5e15189, __VMLINUX_SYMBOL_STR(sock_register) },
	{ 0xbb58620c, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x8336bc73, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x2d735ff0, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0xf1917db5, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x62737e1d, __VMLINUX_SYMBOL_STR(sock_unregister) },
	{ 0x75b05a12, __VMLINUX_SYMBOL_STR(xfrm_unregister_km) },
	{ 0x7a8ca627, __VMLINUX_SYMBOL_STR(xfrm_count_pfkey_enc_supported) },
	{ 0xa575945, __VMLINUX_SYMBOL_STR(xfrm_count_pfkey_auth_supported) },
	{ 0x28e23139, __VMLINUX_SYMBOL_STR(xfrm_probe_algs) },
	{ 0x4708f65d, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x5bb499fc, __VMLINUX_SYMBOL_STR(xfrm_state_delete) },
	{ 0xc2488580, __VMLINUX_SYMBOL_STR(xfrm_audit_state_delete) },
	{ 0x5afd2e36, __VMLINUX_SYMBOL_STR(xfrm_state_lookup) },
	{ 0xe2dbf4f9, __VMLINUX_SYMBOL_STR(xfrm_alloc_spi) },
	{ 0xf10526ac, __VMLINUX_SYMBOL_STR(verify_spi_info) },
	{ 0x8baff67a, __VMLINUX_SYMBOL_STR(xfrm_find_acq) },
	{ 0x47b34e60, __VMLINUX_SYMBOL_STR(xfrm_ealg_get_byname) },
	{ 0x3bf471d7, __VMLINUX_SYMBOL_STR(xfrm_calg_get_byname) },
	{ 0xa6e66685, __VMLINUX_SYMBOL_STR(xfrm_aalg_get_byname) },
	{ 0xdbfc35c8, __VMLINUX_SYMBOL_STR(xfrm_ealg_get_byidx) },
	{ 0xaa762fe2, __VMLINUX_SYMBOL_STR(xfrm_aalg_get_byidx) },
	{ 0xeec4d934, __VMLINUX_SYMBOL_STR(xfrm_policy_byid) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xac445e7b, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0x661d549f, __VMLINUX_SYMBOL_STR(copy_from_iter) },
	{ 0xad1b60ed, __VMLINUX_SYMBOL_STR(xfrm_calg_get_byid) },
	{ 0x834ba96d, __VMLINUX_SYMBOL_STR(xfrm_aalg_get_byid) },
	{ 0x61764834, __VMLINUX_SYMBOL_STR(xfrm_state_add) },
	{ 0x23ce9c58, __VMLINUX_SYMBOL_STR(xfrm_audit_state_add) },
	{ 0xda9ffdd6, __VMLINUX_SYMBOL_STR(xfrm_state_update) },
	{ 0x2e18e166, __VMLINUX_SYMBOL_STR(xfrm_init_state) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0xdfea3a6d, __VMLINUX_SYMBOL_STR(xfrm_ealg_get_byid) },
	{ 0xaad2c0c3, __VMLINUX_SYMBOL_STR(xfrm_state_alloc) },
	{ 0xedb6bb2c, __VMLINUX_SYMBOL_STR(xfrm_audit_policy_add) },
	{ 0x5d5ccde2, __VMLINUX_SYMBOL_STR(xfrm_policy_insert) },
	{ 0x5ee5d0d6, __VMLINUX_SYMBOL_STR(xfrm_garbage_collect) },
	{ 0xa1588d8c, __VMLINUX_SYMBOL_STR(xfrm_audit_policy_delete) },
	{ 0xfe2b5047, __VMLINUX_SYMBOL_STR(xfrm_policy_bysel_ctx) },
	{ 0x1e9edfb7, __VMLINUX_SYMBOL_STR(seq_hlist_start_head_rcu) },
	{ 0x67b78eb3, __VMLINUX_SYMBOL_STR(seq_hlist_next_rcu) },
	{ 0x4caa3b97, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x6370234b, __VMLINUX_SYMBOL_STR(from_kuid_munged) },
	{ 0xfb9aec27, __VMLINUX_SYMBOL_STR(sock_i_uid) },
	{ 0x28cc8f7e, __VMLINUX_SYMBOL_STR(sock_i_ino) },
	{ 0xb2989195, __VMLINUX_SYMBOL_STR(seq_open_net) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0xf0eaffce, __VMLINUX_SYMBOL_STR(_raw_write_unlock_bh) },
	{ 0x15799c11, __VMLINUX_SYMBOL_STR(_raw_write_lock_bh) },
	{ 0x3269ac39, __VMLINUX_SYMBOL_STR(__xfrm_state_destroy) },
	{ 0xbba70a2d, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0xd9d3bcd3, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0xc187bb8d, __VMLINUX_SYMBOL_STR(xfrm_find_acq_byseq) },
	{ 0x252b27b6, __VMLINUX_SYMBOL_STR(km_state_notify) },
	{ 0xc68c4645, __VMLINUX_SYMBOL_STR(xfrm_state_flush) },
	{ 0xe43ebf82, __VMLINUX_SYMBOL_STR(xfrm_state_walk) },
	{ 0x3780bf60, __VMLINUX_SYMBOL_STR(xfrm_state_walk_done) },
	{ 0x83b009ea, __VMLINUX_SYMBOL_STR(xfrm_state_walk_init) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x3dd9b922, __VMLINUX_SYMBOL_STR(skb_copy) },
	{ 0x94826275, __VMLINUX_SYMBOL_STR(km_policy_notify) },
	{ 0xac42ae25, __VMLINUX_SYMBOL_STR(xfrm_policy_flush) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x28db0cc6, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x76d63a1e, __VMLINUX_SYMBOL_STR(sock_init_data) },
	{ 0xdc6f607, __VMLINUX_SYMBOL_STR(sk_alloc) },
	{ 0x9ed2d311, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0xf033b983, __VMLINUX_SYMBOL_STR(__sock_recv_ts_and_drops) },
	{ 0xbde8487c, __VMLINUX_SYMBOL_STR(skb_free_datagram) },
	{ 0x9abd39, __VMLINUX_SYMBOL_STR(skb_copy_datagram_iter) },
	{ 0x4d4d7ce0, __VMLINUX_SYMBOL_STR(skb_recv_datagram) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x30df9d26, __VMLINUX_SYMBOL_STR(skb_queue_purge) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf8708a4d, __VMLINUX_SYMBOL_STR(xfrm_policy_destroy) },
	{ 0xacf3e831, __VMLINUX_SYMBOL_STR(xfrm_policy_alloc) },
	{ 0x73bf95ec, __VMLINUX_SYMBOL_STR(xfrm_policy_walk_done) },
	{ 0xe5ed5467, __VMLINUX_SYMBOL_STR(xfrm_policy_walk_init) },
	{ 0xd1b16c13, __VMLINUX_SYMBOL_STR(xfrm_policy_walk) },
	{ 0x69528d1f, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x25e2755b, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0xdcfe16f3, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x32d47abc, __VMLINUX_SYMBOL_STR(skb_queue_tail) },
	{ 0x1f31871e, __VMLINUX_SYMBOL_STR(sock_rfree) },
	{ 0x9f9d8024, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xbf145237, __VMLINUX_SYMBOL_STR(__alloc_skb) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=xfrm_algo";

