#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x7f79f024, __VMLINUX_SYMBOL_STR(kvm_apic_write_nodecode) },
	{ 0xd0b2727a, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mask_ptes) },
	{ 0x122e6e41, __VMLINUX_SYMBOL_STR(cpu_tss) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x20eacf76, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0x4fa2f98, __VMLINUX_SYMBOL_STR(kvm_vcpu_write_guest) },
	{ 0x7991fd8d, __VMLINUX_SYMBOL_STR(crash_vmclear_loaded_vmcss) },
	{ 0x1aabee07, __VMLINUX_SYMBOL_STR(kvm_cpu_get_interrupt) },
	{ 0x1f1c4d73, __VMLINUX_SYMBOL_STR(kvm_mmu_sync_roots) },
	{ 0xe14a5330, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0xc1c46cb5, __VMLINUX_SYMBOL_STR(kvm_inject_page_fault) },
	{ 0xc1ce9a5a, __VMLINUX_SYMBOL_STR(kvm_require_dr) },
	{ 0x64020e10, __VMLINUX_SYMBOL_STR(kvm_set_shared_msr) },
	{ 0x686a6716, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x4ef11b3d, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
	{ 0x20550da4, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x44ad0c87, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0xdfd1d9d8, __VMLINUX_SYMBOL_STR(kvm_inject_realmode_interrupt) },
	{ 0x42e7d72c, __VMLINUX_SYMBOL_STR(kvm_vcpu_kick) },
	{ 0x3e6ee0f9, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0x433d4979, __VMLINUX_SYMBOL_STR(kvm_apic_set_eoi_accelerated) },
	{ 0xb581290c, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x726d61e7, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0x86371acd, __VMLINUX_SYMBOL_STR(ex_handler_rdmsr_unsafe) },
	{ 0xbaf9522e, __VMLINUX_SYMBOL_STR(hrtimer_cancel) },
	{ 0xc5c87630, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0xeb59e8c3, __VMLINUX_SYMBOL_STR(native_load_gs_index) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0x6b8ae014, __VMLINUX_SYMBOL_STR(__srcu_read_unlock) },
	{ 0xd81c4515, __VMLINUX_SYMBOL_STR(__hrtimer_get_remaining) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xa48945a4, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0x299f4d11, __VMLINUX_SYMBOL_STR(kvm_mmu_unload) },
	{ 0xeb342330, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x16cd74d7, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0xb0b9afdc, __VMLINUX_SYMBOL_STR(kvm_mtrr_get_guest_memory_type) },
	{ 0x21ef77c8, __VMLINUX_SYMBOL_STR(kvm_vcpu_reload_apic_access_page) },
	{ 0xa50b6b56, __VMLINUX_SYMBOL_STR(ex_handler_clear_fs) },
	{ 0x9e030a9f, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xbf5a49c4, __VMLINUX_SYMBOL_STR(kvm_mmu_page_fault) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0xbe6e55f2, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0xa0082384, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0x9a9f570f, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xd659e00c, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0x213fdf8c, __VMLINUX_SYMBOL_STR(__x86_set_memory_region) },
	{ 0xec7e0067, __VMLINUX_SYMBOL_STR(kvm_release_page_clean) },
	{ 0xed7101c8, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc599bc18, __VMLINUX_SYMBOL_STR(kvm_max_tsc_scaling_ratio) },
	{ 0x79b6875, __VMLINUX_SYMBOL_STR(hrtimer_start_range_ns) },
	{ 0x26d4f2cf, __VMLINUX_SYMBOL_STR(x86_set_memory_region) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xedc3a98, __VMLINUX_SYMBOL_STR(kvm_mmu_unprotect_page_virt) },
	{ 0x96dbe382, __VMLINUX_SYMBOL_STR(kvm_mpx_supported) },
	{ 0x5123cf99, __VMLINUX_SYMBOL_STR(handle_mmio_page_fault) },
	{ 0xd86cd219, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0x61f40a5b, __VMLINUX_SYMBOL_STR(kvm_get_msr) },
	{ 0x1065da47, __VMLINUX_SYMBOL_STR(kvm_write_tsc) },
	{ 0x80a03979, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xcfb21083, __VMLINUX_SYMBOL_STR(kvm_get_linear_rip) },
	{ 0xd0459e67, __VMLINUX_SYMBOL_STR(kvm_has_tsc_control) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0xdfe2f47d, __VMLINUX_SYMBOL_STR(ex_handler_wrmsr_unsafe) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x3865ccad, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0x3052ab44, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0x3e1f72e0, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0xab844ce0, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0x578f958b, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0x9fe09c18, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3b91db5b, __VMLINUX_SYMBOL_STR(intel_pt_handle_vmx) },
	{ 0x28db0cc6, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xc507a89f, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0xda892ad7, __VMLINUX_SYMBOL_STR(kvm_emulate_wbinvd) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0x825b14f, __VMLINUX_SYMBOL_STR(kvm_apic_update_irr) },
	{ 0x52055c4, __VMLINUX_SYMBOL_STR(__srcu_read_lock) },
	{ 0xb6a68816, __VMLINUX_SYMBOL_STR(find_last_bit) },
	{ 0x26998144, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0x15a56225, __VMLINUX_SYMBOL_STR(kvm_scale_tsc) },
	{ 0xea628e36, __VMLINUX_SYMBOL_STR(cpu_bit_bitmap) },
	{ 0xc56d75ce, __VMLINUX_SYMBOL_STR(__kvm_apic_update_irr) },
	{ 0x394f5fc0, __VMLINUX_SYMBOL_STR(kvm_cpu_has_interrupt) },
	{ 0x17ad91bc, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_set_dirty) },
	{ 0x2027d68b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0xf2f286c4, __VMLINUX_SYMBOL_STR(kvm_tsc_scaling_ratio_frac_bits) },
	{ 0xbde3fc81, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_leaf_clear_dirty) },
	{ 0x7562656, __VMLINUX_SYMBOL_STR(kvm_valid_efer) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x48f8fc97, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xc287d96a, __VMLINUX_SYMBOL_STR(kvm_set_posted_intr_wakeup_handler) },
	{ 0x582cc5, __VMLINUX_SYMBOL_STR(kvm_write_guest_page) },
	{ 0xc234a084, __VMLINUX_SYMBOL_STR(kvm_vcpu_is_reset_bsp) },
	{ 0xedc2aede, __VMLINUX_SYMBOL_STR(cpu_tlbstate) },
	{ 0x93fca811, __VMLINUX_SYMBOL_STR(__get_free_pages) },
	{ 0x579109ae, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0x2df88a12, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xc0cd3b13, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xf110efae, __VMLINUX_SYMBOL_STR(kvm_lapic_set_eoi) },
	{ 0xc7d197f1, __VMLINUX_SYMBOL_STR(kvm_lmsw) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x37153e53, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0xcaae2b03, __VMLINUX_SYMBOL_STR(kvm_init_shadow_ept_mmu) },
	{ 0x67dade7a, __VMLINUX_SYMBOL_STR(kvm_require_cpl) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0xebc7f9bc, __VMLINUX_SYMBOL_STR(kvm_mmu_clear_dirty_pt_masked) },
	{ 0xba9ed435, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mmio_spte_mask) },
	{ 0x3b1a1608, __VMLINUX_SYMBOL_STR(kvm_io_bus_write) },
	{ 0x4f289df4, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0x38fd76ed, __VMLINUX_SYMBOL_STR(kvm_vcpu_gfn_to_page) },
	{ 0x76649161, __VMLINUX_SYMBOL_STR(kvm_read_guest_virt) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0x4ca98f9b, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0xce9058ce, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0xa18bb283, __VMLINUX_SYMBOL_STR(kvm_write_guest_virt_system) },
	{ 0x957d3791, __VMLINUX_SYMBOL_STR(perf_event_read_value) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x280f9f14, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x815ed091, __VMLINUX_SYMBOL_STR(kvm_mtrr_valid) },
	{ 0xa66ad3c9, __VMLINUX_SYMBOL_STR(reprogram_gp_counter) },
	{ 0xb35a6656, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0x9a216313, __VMLINUX_SYMBOL_STR(kvm_define_shared_msr) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0x1226bdb6, __VMLINUX_SYMBOL_STR(ex_handler_default) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x8e88769e, __VMLINUX_SYMBOL_STR(kvm_set_apic_base) },
	{ 0x59703832, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0x691eee9b, __VMLINUX_SYMBOL_STR(kvm_arch_has_noncoherent_dma) },
	{ 0xff91f164, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xd815516f, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_largepage_remove_write_access) },
	{ 0xe70cb3b4, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0xbc884208, __VMLINUX_SYMBOL_STR(reprogram_fixed_counter) },
	{ 0x71451794, __VMLINUX_SYMBOL_STR(hrtimer_init) },
	{ 0x959f4b42, __VMLINUX_SYMBOL_STR(kvm_no_apic_vcpu) },
	{ 0xecad3b34, __VMLINUX_SYMBOL_STR(do_machine_check) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0x686daa3d, __VMLINUX_SYMBOL_STR(gfn_to_page) },
	{ 0xac0b71ba, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0xab8b8619, __VMLINUX_SYMBOL_STR(apic) },
	{ 0xb53b8ef7, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x439ec1d5, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0x88e79171, __VMLINUX_SYMBOL_STR(reprogram_counter) },
	{ 0x48682db9, __VMLINUX_SYMBOL_STR(perf_guest_get_msrs) },
	{ 0x20de5193, __VMLINUX_SYMBOL_STR(kvm_disable_largepages) },
	{ 0xf2d5db20, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x37dcc122, __VMLINUX_SYMBOL_STR(kvm_clear_guest_page) },
	{ 0x2928381b, __VMLINUX_SYMBOL_STR(kvm_vcpu_halt) },
	{ 0x6228c21f, __VMLINUX_SYMBOL_STR(smp_call_function_single) },
	{ 0xbe8a4b35, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x60ce210c, __VMLINUX_SYMBOL_STR(kvm_vcpu_mark_page_dirty) },
	{ 0x2c61b411, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
	{ 0x1c6f7ccd, __VMLINUX_SYMBOL_STR(kvm_arch_has_assigned_device) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("cpu:type:x86,ven*fam*mod*:feature:*0085*");
