#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf1f94d15, __VMLINUX_SYMBOL_STR(snd_hdac_power_up) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x402b8281, __VMLINUX_SYMBOL_STR(__request_module) },
	{ 0x122e6e41, __VMLINUX_SYMBOL_STR(cpu_tss) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xd9a8cd89, __VMLINUX_SYMBOL_STR(snd_hdac_stream_start) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xd15774fc, __VMLINUX_SYMBOL_STR(driver_register) },
	{ 0x4a34c3b4, __VMLINUX_SYMBOL_STR(pm_runtime_force_suspend) },
	{ 0x36d41140, __VMLINUX_SYMBOL_STR(snd_hdac_refresh_widget_sysfs) },
	{ 0x182a7e31, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x63082fd8, __VMLINUX_SYMBOL_STR(snd_pcm_lib_default_mmap) },
	{ 0x686a6716, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xa286e059, __VMLINUX_SYMBOL_STR(snd_hdac_codec_read) },
	{ 0x32f00b0, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x9a8e1877, __VMLINUX_SYMBOL_STR(snd_array_free) },
	{ 0xd78489c7, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_step) },
	{ 0xfe15ac18, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0x52683e4b, __VMLINUX_SYMBOL_STR(snd_hdac_stream_reset) },
	{ 0x3f64cc6, __VMLINUX_SYMBOL_STR(snd_hdac_link_power) },
	{ 0xddb541f6, __VMLINUX_SYMBOL_STR(snd_device_free) },
	{ 0x137136c1, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync_trigger) },
	{ 0xbe7dd7dc, __VMLINUX_SYMBOL_STR(snd_array_new) },
	{ 0xb641acc2, __VMLINUX_SYMBOL_STR(snd_info_create_card_entry) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x4caa3b97, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xe83d2ee4, __VMLINUX_SYMBOL_STR(snd_pci_quirk_lookup) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x8316cc48, __VMLINUX_SYMBOL_STR(pm_runtime_force_resume) },
	{ 0x6334d29e, __VMLINUX_SYMBOL_STR(snd_hdac_bus_handle_stream_irq) },
	{ 0xa869f7c6, __VMLINUX_SYMBOL_STR(snd_device_disconnect) },
	{ 0x491eb1d3, __VMLINUX_SYMBOL_STR(snd_hdac_get_sub_nodes) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0xb805cc02, __VMLINUX_SYMBOL_STR(snd_hdac_stream_set_params) },
	{ 0xe5178584, __VMLINUX_SYMBOL_STR(snd_hdac_stream_setup) },
	{ 0x6f8c9737, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xab757cde, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xeb53bc12, __VMLINUX_SYMBOL_STR(pm_runtime_allow) },
	{ 0x37815e85, __VMLINUX_SYMBOL_STR(snd_hdac_device_exit) },
	{ 0x404be8cd, __VMLINUX_SYMBOL_STR(pm_runtime_forbid) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0xa29c73d0, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_integer) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xa6c875fc, __VMLINUX_SYMBOL_STR(snd_hda_bus_type) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x28598629, __VMLINUX_SYMBOL_STR(_snd_ctl_add_slave) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x575b7ed8, __VMLINUX_SYMBOL_STR(snd_pcm_suspend_all) },
	{ 0x53d88ef3, __VMLINUX_SYMBOL_STR(snd_hdac_check_power_state) },
	{ 0xd24da8f8, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_exit) },
	{ 0x2af0d06c, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x561f9186, __VMLINUX_SYMBOL_STR(snd_device_new) },
	{ 0xfd952d4e, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_write_raw) },
	{ 0x77bedc94, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x2e2b40d2, __VMLINUX_SYMBOL_STR(strncat) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0xa19170bb, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync) },
	{ 0x96494af4, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_cmd_io) },
	{ 0x99eb629f, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xe6718f32, __VMLINUX_SYMBOL_STR(snd_pcm_set_ops) },
	{ 0xf15bd57e, __VMLINUX_SYMBOL_STR(driver_unregister) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0xd0609cd6, __VMLINUX_SYMBOL_STR(snd_hdac_device_set_chip_name) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x2132222a, __VMLINUX_SYMBOL_STR(snd_hdac_power_down_pm) },
	{ 0x28db0cc6, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed5a24fa, __VMLINUX_SYMBOL_STR(device_attach) },
	{ 0xc423dbee, __VMLINUX_SYMBOL_STR(snd_hdac_read) },
	{ 0x9dbf81a3, __VMLINUX_SYMBOL_STR(snd_hwdep_new) },
	{ 0x37183a68, __VMLINUX_SYMBOL_STR(snd_jack_new) },
	{ 0x99eb5ee5, __VMLINUX_SYMBOL_STR(snd_hdac_stream_assign) },
	{ 0x5d4a8320, __VMLINUX_SYMBOL_STR(kvasprintf) },
	{ 0x6b376393, __VMLINUX_SYMBOL_STR(snd_hdac_device_init) },
	{ 0x6c59ed0c, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0xb6f906ca, __VMLINUX_SYMBOL_STR(snd_hdac_device_unregister) },
	{ 0xe3a53f4c, __VMLINUX_SYMBOL_STR(sort) },
	{ 0x14f10401, __VMLINUX_SYMBOL_STR(snd_hdac_stream_init) },
	{ 0x7381187e, __VMLINUX_SYMBOL_STR(snd_hdac_read_parm_uncached) },
	{ 0xdd9a804a, __VMLINUX_SYMBOL_STR(snd_hdac_calc_stream_format) },
	{ 0xb9d02d40, __VMLINUX_SYMBOL_STR(snd_ctl_boolean_mono_info) },
	{ 0xbd66b271, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init) },
	{ 0xc542933a, __VMLINUX_SYMBOL_STR(timecounter_read) },
	{ 0xd0bd0350, __VMLINUX_SYMBOL_STR(snd_hdac_stream_cleanup) },
	{ 0x81b69e41, __VMLINUX_SYMBOL_STR(snd_ctl_enum_info) },
	{ 0x77506672, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xe702027d, __VMLINUX_SYMBOL_STR(snd_hdac_stream_stop) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x2d24b397, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_chip) },
	{ 0x2868169b, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x695a13be, __VMLINUX_SYMBOL_STR(snd_ctl_make_virtual_master) },
	{ 0xd84b9de1, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_update_raw) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xf9bc64fa, __VMLINUX_SYMBOL_STR(snd_hdac_device_register) },
	{ 0x582629de, __VMLINUX_SYMBOL_STR(snd_component_add) },
	{ 0x654c082e, __VMLINUX_SYMBOL_STR(snd_hdac_override_parm) },
	{ 0x91f4a2af, __VMLINUX_SYMBOL_STR(snd_hdac_bus_exec_verb_unlocked) },
	{ 0x4e1b99f, __VMLINUX_SYMBOL_STR(snd_pcm_std_chmaps) },
	{ 0xaa9a58a3, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0xe1605d7a, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x24d95441, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x109716ec, __VMLINUX_SYMBOL_STR(_snd_hdac_read_parm) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x5c23e9f0, __VMLINUX_SYMBOL_STR(snd_ctl_new1) },
	{ 0x211f68f1, __VMLINUX_SYMBOL_STR(getnstimeofday64) },
	{ 0x4ecc3ad8, __VMLINUX_SYMBOL_STR(snd_hdac_stream_timecounter_init) },
	{ 0x55ba43d7, __VMLINUX_SYMBOL_STR(snd_pcm_set_sync) },
	{ 0x123f82f3, __VMLINUX_SYMBOL_STR(getrawmonotonic64) },
	{ 0xa68c9498, __VMLINUX_SYMBOL_STR(snd_ctl_find_id) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xe143e7f, __VMLINUX_SYMBOL_STR(snd_ctl_remove) },
	{ 0x5ccbba7d, __VMLINUX_SYMBOL_STR(snd_ctl_sync_vmaster) },
	{ 0x85041c37, __VMLINUX_SYMBOL_STR(regcache_mark_dirty) },
	{ 0x8e81b76b, __VMLINUX_SYMBOL_STR(snd_ctl_add_vmaster_hook) },
	{ 0x54ab5af, __VMLINUX_SYMBOL_STR(snd_hdac_query_supported_pcm) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x747470ac, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_chip) },
	{ 0x50aff111, __VMLINUX_SYMBOL_STR(snd_hdac_codec_modalias) },
	{ 0x6128b5fc, __VMLINUX_SYMBOL_STR(__printk_ratelimit) },
	{ 0xc0180a99, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_minmax) },
	{ 0xe70df4ef, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_init) },
	{ 0x499af318, __VMLINUX_SYMBOL_STR(snd_hdac_codec_write) },
	{ 0xbee3384, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0x9dcba3b8, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0xf1671b86, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xd9cd552f, __VMLINUX_SYMBOL_STR(snd_card_register) },
	{ 0xa9bc3d04, __VMLINUX_SYMBOL_STR(snd_pcm_add_chmap_ctls) },
	{ 0x342e94e0, __VMLINUX_SYMBOL_STR(snd_hdac_power_down) },
	{ 0xb4b72b51, __VMLINUX_SYMBOL_STR(snd_hdac_bus_update_rirb) },
	{ 0x9646f0ba, __VMLINUX_SYMBOL_STR(snd_pcm_limit_hw_rates) },
	{ 0xd0cec2ab, __VMLINUX_SYMBOL_STR(snd_jack_report) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x61339424, __VMLINUX_SYMBOL_STR(snd_pcm_new) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x29096c7f, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_read_raw) },
	{ 0x37abb417, __VMLINUX_SYMBOL_STR(snd_hdac_is_supported_format) },
	{ 0x929aee48, __VMLINUX_SYMBOL_STR(snd_ctl_add) },
	{ 0xd56b5f64, __VMLINUX_SYMBOL_STR(ktime_get_ts64) },
	{ 0x7f02188f, __VMLINUX_SYMBOL_STR(__msecs_to_jiffies) },
	{ 0x7c7da87d, __VMLINUX_SYMBOL_STR(snd_hdac_bus_send_cmd) },
	{ 0xd28b6d8, __VMLINUX_SYMBOL_STR(regcache_sync) },
	{ 0x7eb3fa2f, __VMLINUX_SYMBOL_STR(regcache_cache_only) },
	{ 0x8f134482, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xda70aaf5, __VMLINUX_SYMBOL_STR(snd_hdac_power_up_pm) },
	{ 0xc2af5440, __VMLINUX_SYMBOL_STR(snd_hdac_get_connections) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x2af828a0, __VMLINUX_SYMBOL_STR(snd_hdac_stream_release) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-hda-core,snd-pcm,snd,snd-hwdep";

