#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6cc42aee, __VMLINUX_SYMBOL_STR(proc_dointvec_minmax) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xc897c382, __VMLINUX_SYMBOL_STR(sg_init_table) },
	{ 0xb6306e83, __VMLINUX_SYMBOL_STR(xprt_lookup_rqst) },
	{ 0x4489da02, __VMLINUX_SYMBOL_STR(register_sysctl_table) },
	{ 0x2c8e26c, __VMLINUX_SYMBOL_STR(ib_dealloc_pd) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xfc5144f4, __VMLINUX_SYMBOL_STR(ib_drain_qp) },
	{ 0xc23d8c4, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x4397eed5, __VMLINUX_SYMBOL_STR(svc_xprt_enqueue) },
	{ 0x5e50060f, __VMLINUX_SYMBOL_STR(svc_reg_xprt_class) },
	{ 0xd9d3bcd3, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x5e38d055, __VMLINUX_SYMBOL_STR(xprt_register_transport) },
	{ 0x3148a87, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x23946dd0, __VMLINUX_SYMBOL_STR(rdma_accept) },
	{ 0x4caa3b97, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xbc84c37a, __VMLINUX_SYMBOL_STR(xprt_free) },
	{ 0xeca66e4d, __VMLINUX_SYMBOL_STR(rdma_destroy_id) },
	{ 0x6f8c9737, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x2c75dd40, __VMLINUX_SYMBOL_STR(ib_free_cq) },
	{ 0xab757cde, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xfa822ba, __VMLINUX_SYMBOL_STR(xprt_alloc) },
	{ 0xc0dff5a5, __VMLINUX_SYMBOL_STR(rpcb_getport_async) },
	{ 0x3b0da2b9, __VMLINUX_SYMBOL_STR(xprt_wake_pending_tasks) },
	{ 0xe5840ec6, __VMLINUX_SYMBOL_STR(ib_wc_status_msg) },
	{ 0x9a9f570f, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x14ef600c, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x2357de15, __VMLINUX_SYMBOL_STR(rdma_connect) },
	{ 0x7cd666bb, __VMLINUX_SYMBOL_STR(svc_unreg_xprt_class) },
	{ 0x8a0b12c6, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xc671e369, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x1e491a04, __VMLINUX_SYMBOL_STR(ib_unmap_fmr) },
	{ 0x5f3dd052, __VMLINUX_SYMBOL_STR(ib_alloc_mr) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xb0eb2a81, __VMLINUX_SYMBOL_STR(svc_xprt_init) },
	{ 0xc1a25dc3, __VMLINUX_SYMBOL_STR(ib_alloc_pd) },
	{ 0x80a03979, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x7d939033, __VMLINUX_SYMBOL_STR(ib_get_dma_mr) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xb9d6b074, __VMLINUX_SYMBOL_STR(rdma_destroy_qp) },
	{ 0x1df6b5d0, __VMLINUX_SYMBOL_STR(rdma_listen) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x677701e8, __VMLINUX_SYMBOL_STR(xprt_unregister_transport) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4a3cbabe, __VMLINUX_SYMBOL_STR(rdma_set_afonly) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xc5bdc8ae, __VMLINUX_SYMBOL_STR(svc_xprt_copy_addrs) },
	{ 0x7ba8b474, __VMLINUX_SYMBOL_STR(xprt_release_xprt_cong) },
	{ 0x5f16170e, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xccd990be, __VMLINUX_SYMBOL_STR(rdma_create_id) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0x2027d68b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xd724965b, __VMLINUX_SYMBOL_STR(ib_map_mr_sg) },
	{ 0xe0cc30ab, __VMLINUX_SYMBOL_STR(rdma_create_qp) },
	{ 0xf574136, __VMLINUX_SYMBOL_STR(svc_xprt_put) },
	{ 0x15df0843, __VMLINUX_SYMBOL_STR(rdma_bind_addr) },
	{ 0x77506672, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x841c1996, __VMLINUX_SYMBOL_STR(rdma_resolve_route) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x8fcd6637, __VMLINUX_SYMBOL_STR(ib_dealloc_fmr) },
	{ 0x80ecea7c, __VMLINUX_SYMBOL_STR(xprt_alloc_slot) },
	{ 0xa06ff399, __VMLINUX_SYMBOL_STR(unregister_sysctl_table) },
	{ 0xbba70a2d, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x24d95441, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x5f992cfa, __VMLINUX_SYMBOL_STR(flush_delayed_work) },
	{ 0x878cd015, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xac7dde7f, __VMLINUX_SYMBOL_STR(xprt_put) },
	{ 0x45d4e354, __VMLINUX_SYMBOL_STR(rdma_disconnect) },
	{ 0x7de13b6a, __VMLINUX_SYMBOL_STR(ib_alloc_fmr) },
	{ 0xde516998, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x272e26cd, __VMLINUX_SYMBOL_STR(ib_query_qp) },
	{ 0x3959750e, __VMLINUX_SYMBOL_STR(ib_dereg_mr) },
	{ 0xdba85156, __VMLINUX_SYMBOL_STR(xprt_complete_rqst) },
	{ 0xcfa2a09f, __VMLINUX_SYMBOL_STR(ib_event_msg) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1f2a9970, __VMLINUX_SYMBOL_STR(rpc_ntop) },
	{ 0xc7b7de36, __VMLINUX_SYMBOL_STR(rpc_wake_up_queued_task) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x4a898bb, __VMLINUX_SYMBOL_STR(xprt_set_retrans_timeout_def) },
	{ 0x449d571, __VMLINUX_SYMBOL_STR(xprt_get) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xbfa562cb, __VMLINUX_SYMBOL_STR(xprt_reserve_xprt_cong) },
	{ 0xce161c7d, __VMLINUX_SYMBOL_STR(rdma_resolve_addr) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x5fc37176, __VMLINUX_SYMBOL_STR(xprt_disconnect_done) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x383f2780, __VMLINUX_SYMBOL_STR(xprt_release_rqst_cong) },
	{ 0x5e37a424, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xbe8a4b35, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x8f134482, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x9cfa7eed, __VMLINUX_SYMBOL_STR(ib_alloc_cq) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=sunrpc,ib_core,rdma_cm";

