#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xa18018bb, __VMLINUX_SYMBOL_STR(rdma_resolve_ip) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x4c8cf71e, __VMLINUX_SYMBOL_STR(ib_send_cm_rej) },
	{ 0x6115a181, __VMLINUX_SYMBOL_STR(iw_cm_listen) },
	{ 0x96fdb472, __VMLINUX_SYMBOL_STR(ib_attach_mcast) },
	{ 0x2f282eae, __VMLINUX_SYMBOL_STR(ib_query_gid) },
	{ 0x9f62fd16, __VMLINUX_SYMBOL_STR(__fib_lookup) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xcfe2d71c, __VMLINUX_SYMBOL_STR(rdma_port_get_link_layer) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x501034ed, __VMLINUX_SYMBOL_STR(roce_gid_type_mask_support) },
	{ 0x951ba46e, __VMLINUX_SYMBOL_STR(ib_sa_join_multicast) },
	{ 0x7d1a5aec, __VMLINUX_SYMBOL_STR(ib_send_cm_req) },
	{ 0xcfadce80, __VMLINUX_SYMBOL_STR(ib_send_cm_dreq) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0xc88f450c, __VMLINUX_SYMBOL_STR(ib_send_cm_rtu) },
	{ 0xccc2b5bd, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xe54fe6bd, __VMLINUX_SYMBOL_STR(iw_cm_init_qp_attr) },
	{ 0x3148a87, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x6cc7c0c7, __VMLINUX_SYMBOL_STR(ib_init_ah_from_path) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0xc4253bc5, __VMLINUX_SYMBOL_STR(iw_cm_reject) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x5c77e01e, __VMLINUX_SYMBOL_STR(iw_cm_accept) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf246f98e, __VMLINUX_SYMBOL_STR(__put_net) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0x49bd3ff9, __VMLINUX_SYMBOL_STR(ib_get_cached_gid) },
	{ 0x163c6607, __VMLINUX_SYMBOL_STR(ib_modify_qp) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xda28a851, __VMLINUX_SYMBOL_STR(ib_send_cm_mra) },
	{ 0x576fdbac, __VMLINUX_SYMBOL_STR(ib_sa_free_multicast) },
	{ 0x7e0af17a, __VMLINUX_SYMBOL_STR(rdma_copy_addr) },
	{ 0xc02c9cf8, __VMLINUX_SYMBOL_STR(ib_get_net_dev_by_params) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x12dbbbb3, __VMLINUX_SYMBOL_STR(ib_create_qp) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x21ec0dbf, __VMLINUX_SYMBOL_STR(ib_send_cm_drep) },
	{ 0xb701528c, __VMLINUX_SYMBOL_STR(ib_cm_init_qp_attr) },
	{ 0xf1917db5, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x809388ca, __VMLINUX_SYMBOL_STR(idr_destroy) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x80a03979, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xedbb7564, __VMLINUX_SYMBOL_STR(__ethtool_get_link_ksettings) },
	{ 0x99eb629f, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xebb8f0e7, __VMLINUX_SYMBOL_STR(iw_cm_disconnect) },
	{ 0xd5d7e998, __VMLINUX_SYMBOL_STR(ibnl_put_attr) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x90e807c7, __VMLINUX_SYMBOL_STR(ib_cache_gid_parse_type_str) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x98676a68, __VMLINUX_SYMBOL_STR(ib_send_cm_rep) },
	{ 0x58f3ca5a, __VMLINUX_SYMBOL_STR(ib_query_port) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x28db0cc6, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xa13ba6c5, __VMLINUX_SYMBOL_STR(iw_destroy_cm_id) },
	{ 0x90c00be9, __VMLINUX_SYMBOL_STR(dev_get_by_index) },
	{ 0x3859b928, __VMLINUX_SYMBOL_STR(config_group_init_type_name) },
	{ 0xa735db59, __VMLINUX_SYMBOL_STR(prandom_u32) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0x7ecded72, __VMLINUX_SYMBOL_STR(configfs_register_subsystem) },
	{ 0xcd8a78db, __VMLINUX_SYMBOL_STR(ib_get_cached_pkey) },
	{ 0x5f16170e, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x4bc54258, __VMLINUX_SYMBOL_STR(ib_set_client_data) },
	{ 0x1501cd3b, __VMLINUX_SYMBOL_STR(ib_init_ah_from_mcmember) },
	{ 0x287d1e73, __VMLINUX_SYMBOL_STR(ib_sa_unregister_client) },
	{ 0x87cc0251, __VMLINUX_SYMBOL_STR(vlan_dev_real_dev) },
	{ 0xa377fb6f, __VMLINUX_SYMBOL_STR(ib_create_cm_id) },
	{ 0xb85f7b5c, __VMLINUX_SYMBOL_STR(ib_sa_path_rec_get) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x328dd9b7, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0xda0d50ec, __VMLINUX_SYMBOL_STR(ib_sa_cancel_query) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x81144f9d, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x5b54f0a6, __VMLINUX_SYMBOL_STR(ib_sa_get_mcmember_rec) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x791d736f, __VMLINUX_SYMBOL_STR(ib_detach_mcast) },
	{ 0xe2b3789a, __VMLINUX_SYMBOL_STR(ib_cm_notify) },
	{ 0x5b464fd2, __VMLINUX_SYMBOL_STR(rdma_addr_cancel) },
	{ 0xc1968ca6, __VMLINUX_SYMBOL_STR(iw_cm_connect) },
	{ 0xc0cd3b13, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x1fbd16da, __VMLINUX_SYMBOL_STR(ip_tos2prio) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xf8389154, __VMLINUX_SYMBOL_STR(ib_find_cached_pkey) },
	{ 0x86e535f6, __VMLINUX_SYMBOL_STR(ip_mc_inc_group) },
	{ 0xbb58620c, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x9d9cabc5, __VMLINUX_SYMBOL_STR(rdma_addr_register_client) },
	{ 0x9df03314, __VMLINUX_SYMBOL_STR(configfs_unregister_subsystem) },
	{ 0x1edc4064, __VMLINUX_SYMBOL_STR(rdma_addr_unregister_client) },
	{ 0x5611cdea, __VMLINUX_SYMBOL_STR(rdma_node_get_transport) },
	{ 0xb3d36b1b, __VMLINUX_SYMBOL_STR(ib_destroy_cm_id) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x3c157e9a, __VMLINUX_SYMBOL_STR(ibnl_add_client) },
	{ 0x1c3c0ad3, __VMLINUX_SYMBOL_STR(rdma_addr_size) },
	{ 0x83475566, __VMLINUX_SYMBOL_STR(fib_table_lookup) },
	{ 0x975c612, __VMLINUX_SYMBOL_STR(rdma_translate_ip) },
	{ 0xf80a5e90, __VMLINUX_SYMBOL_STR(rt6_lookup) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x5f51c4a, __VMLINUX_SYMBOL_STR(ib_sa_register_client) },
	{ 0xc67f14a5, __VMLINUX_SYMBOL_STR(ibnl_remove_client) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xc6abfd7, __VMLINUX_SYMBOL_STR(ib_cm_insert_listen) },
	{ 0xce19d1f0, __VMLINUX_SYMBOL_STR(ib_find_cached_gid_by_port) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0x6bc8a60e, __VMLINUX_SYMBOL_STR(ibnl_put_msg) },
	{ 0x5a01b70a, __VMLINUX_SYMBOL_STR(ip_mc_dec_group) },
	{ 0x2b1000a7, __VMLINUX_SYMBOL_STR(config_group_init) },
	{ 0xe1ced72a, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_rep) },
	{ 0x1f29c244, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0xa934c0cd, __VMLINUX_SYMBOL_STR(inet_get_local_port_range) },
	{ 0x48172a7c, __VMLINUX_SYMBOL_STR(iw_create_cm_id) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x2a91bb33, __VMLINUX_SYMBOL_STR(ib_cache_gid_type_str) },
	{ 0x1f857391, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_req) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ib_core,ib_cm,iw_cm,ipv6";

