#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6cc42aee, __VMLINUX_SYMBOL_STR(proc_dointvec_minmax) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x822a415, __VMLINUX_SYMBOL_STR(locks_copy_lock) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x6b954705, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x619cb7dd, __VMLINUX_SYMBOL_STR(simple_read_from_buffer) },
	{ 0x4489da02, __VMLINUX_SYMBOL_STR(register_sysctl_table) },
	{ 0x32f95274, __VMLINUX_SYMBOL_STR(param_get_int) },
	{ 0xdc4ef4d2, __VMLINUX_SYMBOL_STR(locks_start_grace) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xf68285c0, __VMLINUX_SYMBOL_STR(register_inetaddr_notifier) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x911186d6, __VMLINUX_SYMBOL_STR(svc_print_addr) },
	{ 0xad6b8301, __VMLINUX_SYMBOL_STR(svc_sock_update_bufs) },
	{ 0x8507c383, __VMLINUX_SYMBOL_STR(proc_dointvec) },
	{ 0x7ab88a45, __VMLINUX_SYMBOL_STR(system_freezing_cnt) },
	{ 0xc3880471, __VMLINUX_SYMBOL_STR(xdr_decode_netobj) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x997540c1, __VMLINUX_SYMBOL_STR(svc_find_xprt) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x4708f65d, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x60352082, __VMLINUX_SYMBOL_STR(register_inet6addr_notifier) },
	{ 0x2a78c45b, __VMLINUX_SYMBOL_STR(rpc_restart_call) },
	{ 0x9e030a9f, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x6f8c9737, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xab757cde, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x2664dde1, __VMLINUX_SYMBOL_STR(rpc_force_rebind) },
	{ 0x87278024, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x5cd8cd7b, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0xeeef521e, __VMLINUX_SYMBOL_STR(svc_set_client) },
	{ 0xf995798a, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x9878745c, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2fe252cc, __VMLINUX_SYMBOL_STR(unregister_inet6addr_notifier) },
	{ 0x41aad3ec, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0xd75d3a95, __VMLINUX_SYMBOL_STR(vfs_lock_file) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xf1917db5, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x566b1221, __VMLINUX_SYMBOL_STR(proc_mkdir) },
	{ 0x306bcdba, __VMLINUX_SYMBOL_STR(rpc_call_sync) },
	{ 0xbab3718a, __VMLINUX_SYMBOL_STR(default_llseek) },
	{ 0x75aad241, __VMLINUX_SYMBOL_STR(svc_create) },
	{ 0xd8b1d885, __VMLINUX_SYMBOL_STR(svc_destroy) },
	{ 0x80a03979, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x9a13362, __VMLINUX_SYMBOL_STR(rpc_create) },
	{ 0x13f86f7c, __VMLINUX_SYMBOL_STR(freezing_slow_path) },
	{ 0x99eb629f, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xdc823ee1, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x5d0161ec, __VMLINUX_SYMBOL_STR(proc_doulongvec_minmax) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xd50a8f16, __VMLINUX_SYMBOL_STR(vfs_cancel_lock) },
	{ 0x28db0cc6, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd739ec57, __VMLINUX_SYMBOL_STR(svc_process) },
	{ 0xa07a37f0, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0x96cae550, __VMLINUX_SYMBOL_STR(svc_rpcb_cleanup) },
	{ 0x7e32222a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x5f16170e, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x3a7bca5, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x2a78d6ff, __VMLINUX_SYMBOL_STR(svc_age_temp_xprts_now) },
	{ 0x4a76ad56, __VMLINUX_SYMBOL_STR(flush_signals) },
	{ 0xf574136, __VMLINUX_SYMBOL_STR(svc_xprt_put) },
	{ 0x35d8d7bf, __VMLINUX_SYMBOL_STR(simple_transaction_release) },
	{ 0xdab9c0a, __VMLINUX_SYMBOL_STR(__rpc_wait_for_completion_task) },
	{ 0xfac66aac, __VMLINUX_SYMBOL_STR(svc_create_xprt) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x96d98a05, __VMLINUX_SYMBOL_STR(locks_init_lock) },
	{ 0xfe029963, __VMLINUX_SYMBOL_STR(unregister_inetaddr_notifier) },
	{ 0x18599d2e, __VMLINUX_SYMBOL_STR(locks_release_private) },
	{ 0xa06ff399, __VMLINUX_SYMBOL_STR(unregister_sysctl_table) },
	{ 0x24d95441, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x2eec63c9, __VMLINUX_SYMBOL_STR(xdr_encode_netobj) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xc0cd3b13, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xec8a3b63, __VMLINUX_SYMBOL_STR(locks_lock_inode_wait) },
	{ 0x4482cdb, __VMLINUX_SYMBOL_STR(__refrigerator) },
	{ 0x76dd109b, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x7b840fad, __VMLINUX_SYMBOL_STR(locks_in_grace) },
	{ 0xbb58620c, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x2f5462d, __VMLINUX_SYMBOL_STR(rpc_run_task) },
	{ 0x26bcd58, __VMLINUX_SYMBOL_STR(param_get_ulong) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x1ced4d2, __VMLINUX_SYMBOL_STR(svc_shutdown_net) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1f2a9970, __VMLINUX_SYMBOL_STR(rpc_ntop) },
	{ 0xac445e7b, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0xd8e70f4b, __VMLINUX_SYMBOL_STR(posix_unblock_lock) },
	{ 0x55ac21de, __VMLINUX_SYMBOL_STR(svc_exit_thread) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0xd9cac7f4, __VMLINUX_SYMBOL_STR(vfs_test_lock) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x117dd506, __VMLINUX_SYMBOL_STR(simple_transaction_get) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6df1aaf1, __VMLINUX_SYMBOL_STR(kernel_sigaction) },
	{ 0x3bb5114a, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x9e61bb05, __VMLINUX_SYMBOL_STR(set_freezable) },
	{ 0x6128b5fc, __VMLINUX_SYMBOL_STR(__printk_ratelimit) },
	{ 0xa910076, __VMLINUX_SYMBOL_STR(svc_xprt_do_enqueue) },
	{ 0xae5cc80c, __VMLINUX_SYMBOL_STR(svc_prepare_thread) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1fe1e1ad, __VMLINUX_SYMBOL_STR(locks_end_grace) },
	{ 0xb742fd7, __VMLINUX_SYMBOL_STR(simple_strtol) },
	{ 0xb3eafce7, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xffb493e0, __VMLINUX_SYMBOL_STR(svc_recv) },
	{ 0xab26968a, __VMLINUX_SYMBOL_STR(svc_bind) },
	{ 0xaa613435, __VMLINUX_SYMBOL_STR(rpc_shutdown_client) },
	{ 0xea71ecbf, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x2919b156, __VMLINUX_SYMBOL_STR(xdr_decode_string_inplace) },
	{ 0x8b7c4f54, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0x958d5ff9, __VMLINUX_SYMBOL_STR(svc_wake_up) },
	{ 0x63c271dd, __VMLINUX_SYMBOL_STR(rpc_put_task) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=grace,sunrpc";

