#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x59776590, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xc5d3d297, __VMLINUX_SYMBOL_STR(drm_encoder_index) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2689dbe0, __VMLINUX_SYMBOL_STR(drm_edid_get_monitor_name) },
	{ 0x5d048cbf, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0x8ffd7a43, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x872e8e46, __VMLINUX_SYMBOL_STR(drm_atomic_legacy_backoff) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0x46308a4a, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0x5ceb5947, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x64d8103d, __VMLINUX_SYMBOL_STR(drm_crtc_index) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0xa7393e73, __VMLINUX_SYMBOL_STR(drm_atomic_nonblocking_commit) },
	{ 0x686a6716, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x21126ab3, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0x4fa4dca5, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0x64005ea5, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x1b9788bf, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0x9fedcc0a, __VMLINUX_SYMBOL_STR(drm_modeset_drop_locks) },
	{ 0xc785d849, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0x7fe15c78, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0x5565a0c9, __VMLINUX_SYMBOL_STR(drm_property_create_blob) },
	{ 0x730f026d, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0x3e6309cf, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0x9ebea853, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0xcc7c1afe, __VMLINUX_SYMBOL_STR(i2c_transfer) },
	{ 0xcb5f8894, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0x1456b7f, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x22bcc86f, __VMLINUX_SYMBOL_STR(drm_modeset_backoff) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xb2e1620c, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0x4caa3b97, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0x6798db02, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0x9e030a9f, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x6f8c9737, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xab757cde, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xd35d7c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xa9bd7bb4, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0x74e04504, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_fini) },
	{ 0x154969f0, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x23ca79a3, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0xb85eadfb, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0xffc6c87a, __VMLINUX_SYMBOL_STR(drm_detect_monitor_audio) },
	{ 0xf8f762d3, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x551e04ae, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0xaeca7a43, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x39093736, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0x71d2c581, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcb2340b8, __VMLINUX_SYMBOL_STR(drm_rect_debug_print) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x3b28fd8f, __VMLINUX_SYMBOL_STR(drm_mode_object_reference) },
	{ 0x1b38b6c5, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0x37dea415, __VMLINUX_SYMBOL_STR(drm_atomic_crtc_set_property) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x4f2db6b1, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0xfe51f703, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0x9b32a1d4, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0xcf1ff64c, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0xfadc3980, __VMLINUX_SYMBOL_STR(drm_plane_index) },
	{ 0x953a7963, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xfbe7668e, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x2d3bf2ae, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x99eb629f, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x6682baa6, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0x497b137d, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0xab339e0, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xcb666201, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0xa4f623a8, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0x4c7fb7a6, __VMLINUX_SYMBOL_STR(drm_atomic_plane_set_property) },
	{ 0x43d6b2c6, __VMLINUX_SYMBOL_STR(drm_property_unreference_blob) },
	{ 0xfe4ebc37, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x28db0cc6, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xdbeef281, __VMLINUX_SYMBOL_STR(drm_modeset_legacy_acquire_ctx) },
	{ 0xd97527fc, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0xfc23c27c, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0xffa947cc, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all_ctx) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xf62d1c7, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xd84374b5, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xb904ff8, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0xbb5246af, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0xa9fbba81, __VMLINUX_SYMBOL_STR(drm_crtc_get_hv_timing) },
	{ 0x7730aa3b, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0x2fe7da80, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0xf15e7b38, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0x56ee99e2, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0x87e47cb2, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0x2868169b, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x4544e538, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x50951521, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0xf54c0d07, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0x1424eb3c, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x24d95441, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x3092bfc, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0x14af7e50, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0x2ea1abe4, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x175e4272, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0xbcc88c5f, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0x99ba7e25, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0xedf9bdba, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0x9969c661, __VMLINUX_SYMBOL_STR(drm_atomic_connector_set_property) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x23905155, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0x3963b991, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0x34ce743, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_init) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x172cfe9a, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xaa51d76, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0x86901cce, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0xef442a04, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xe13a27f9, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x5076499d, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0xf3112630, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0xfeb2420f, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x115ad9df, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xb55dc925, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0x78037b60, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0x15166dd5, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x9c322c3, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xf9f97eb, __VMLINUX_SYMBOL_STR(drm_mode_object_unreference) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x2c5f3ef5, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x85f5e2aa, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x6768a54e, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0xc7a4aebe, __VMLINUX_SYMBOL_STR(drm_property_reference_blob) },
	{ 0x4dc68f65, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,i2c-core,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";

